#!/usr/bin/env python3
"""
ALICE Setup Script
Generates encryption keys and helps configure environment variables
"""

import sys
import base64
import secrets
from cryptography.fernet import Fernet

def print_header():
    print("\n" + "=" * 60)
    print("ALICE Setup Wizard")
    print("Automated Logic Inspection & Code Evaluation")
    print("=" * 60 + "\n")

def generate_encryption_key():
    """Generate Fernet encryption key"""
    key = Fernet.generate_key().decode()
    print("✓ Generated Fernet Encryption Key:")
    print(f"  ENCRYPTION_KEY={key}\n")
    return key

def generate_admin_key():
    """Generate admin API key"""
    key = secrets.token_urlsafe(32)
    print("✓ Generated Admin API Key:")
    print(f"  ADMIN_API_KEY={key}\n")
    return key

def encode_email():
    """Encode email address"""
    print("Enter your email address:")
    email = input("  > ").strip()
    encoded = base64.b64encode(email.encode()).decode()
    print(f"\n✓ Base64 Encoded Email:")
    print(f"  EMAIL_USER_B64={encoded}\n")
    return encoded

def encrypt_password(encryption_key):
    """Encrypt email password"""
    print("Enter your email password:")
    password = input("  > ").strip()

    cipher = Fernet(encryption_key.encode())
    encrypted = cipher.encrypt(password.encode())
    encoded = base64.urlsafe_b64encode(encrypted).decode()

    print(f"\n✓ Encrypted Email Password:")
    print(f"  EMAIL_PASS_ENCRYPTED={encoded}\n")
    return encoded

def generate_env_file(encryption_key, admin_key, email_b64, password_encrypted):
    """Generate .env file"""

    print("\nEnter your database URL (PostgreSQL):")
    print("  Example: postgresql://user:password@host:5432/alice")
    db_url = input("  > ").strip()

    print("\nEnter management email address:")
    admin_email = input("  > ").strip()

    env_content = f"""# ALICE Server Environment Configuration
# Generated by setup.py

# Database
DATABASE_URL={db_url}

# Encryption
ENCRYPTION_KEY={encryption_key}

# Email Configuration
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USER_B64={email_b64}
EMAIL_PASS_ENCRYPTED={password_encrypted}

# Admin
ADMIN_EMAIL={admin_email}
ADMIN_API_KEY={admin_key}

# API
API_BASE_URL=https://alice-server.vercel.app
"""

    with open('alice-server/.env', 'w') as f:
        f.write(env_content)

    print("\n✓ Created alice-server/.env file\n")

def main():
    print_header()

    print("This wizard will help you generate secure credentials for ALICE.\n")

    # Generate keys
    encryption_key = generate_encryption_key()
    admin_key = generate_admin_key()
    email_b64 = encode_email()
    password_encrypted = encrypt_password(encryption_key)

    # Generate .env file
    print("\nWould you like to create a .env file? (y/n)")
    if input("  > ").strip().lower() == 'y':
        generate_env_file(encryption_key, admin_key, email_b64, password_encrypted)

    print("\n" + "=" * 60)
    print("Setup Complete!")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Deploy alice-server to Vercel")
    print("2. Set environment variables in Vercel dashboard")
    print("3. Deploy alice-dashboard to Vercel")
    print("4. Run database migrations")
    print("5. Create your first project")
    print("\nSee README.md for detailed instructions.\n")

if __name__ == "__main__":
    main()
