"""
ALICE Email Client
Obfuscated email sending for technical and management reports
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from typing import Optional, List
from datetime import datetime
from .encryption import EncryptionManager


class EmailClient:
    """Secure email client with credential obfuscation"""

    def __init__(self):
        """Initialize email client with obfuscated credentials"""
        self.encryption = EncryptionManager()

        # Deobfuscate credentials
        self.host = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
        self.port = int(os.environ.get('EMAIL_PORT', '587'))

        # Credentials are stored obfuscated in environment
        email_user_b64 = os.environ.get('EMAIL_USER_B64')
        email_pass_encrypted = os.environ.get('EMAIL_PASS_ENCRYPTED')

        if not email_user_b64 or not email_pass_encrypted:
            raise ValueError("Email credentials not configured")

        self.username = self.encryption.deobfuscate_string(email_user_b64)
        self.password = self.encryption.decrypt(email_pass_encrypted)
        self.admin_email = os.environ.get('ADMIN_EMAIL', 'piyoosh.rai@the-algo.com')

    def send_technical_report(
        self,
        to_email: str,
        project_name: str,
        quality_score: int,
        deployment_status: str,
        bugs: List[dict],
        summary: dict,
        html_report: Optional[str] = None
    ) -> bool:
        """
        Send technical report to developer (no grades, no assessments)

        Args:
            to_email: Developer email
            project_name: Project name
            quality_score: Numeric quality score (shown as %)
            deployment_status: APPROVED, BLOCKED, or CAUTION
            bugs: List of bug dictionaries
            summary: Summary statistics
            html_report: Optional HTML attachment

        Returns:
            True if sent successfully
        """
        subject = f"Code Analysis Report - {project_name}"

        # Build plain text report
        body = f"""
{project_name} Analysis Results
{'=' * 60}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}

Quality Score: {quality_score}%
Deployment Status: {deployment_status}

Summary
-------
Files Analyzed: {summary.get('total_files', 0)}
Tests Passed: {summary.get('tests_passed', 0)}
Tests Failed: {summary.get('tests_failed', 0)}
Critical Issues: {summary.get('critical_bugs', 0)}
High Priority Issues: {summary.get('high_bugs', 0)}
Medium Priority Issues: {summary.get('medium_bugs', 0)}

"""

        if deployment_status == 'BLOCKED':
            body += """
╔════════════════════════════════════════════════════════════╗
║                    DEPLOYMENT BLOCKED                      ║
║  Critical issues must be resolved before production deployment  ║
╚════════════════════════════════════════════════════════════╝

"""

        # Add bug details
        if bugs:
            body += "\nIssues Found\n" + ("=" * 60) + "\n\n"

            for i, bug in enumerate(bugs, 1):
                body += f"{i}. [{bug['severity']}] {bug['category']}\n"
                body += f"   Location: {bug.get('file_path', 'N/A')}:{bug.get('line_number', 'N/A')}\n"
                body += f"   Description: {bug['description']}\n"
                if bug.get('impact'):
                    body += f"   Impact: {bug['impact']}\n"
                if bug.get('fix_suggestion'):
                    body += f"   Required Fix: {bug['fix_suggestion']}\n"
                body += "\n"
        else:
            body += "\nNo critical issues found. Code quality looks good!\n"

        body += f"""
---
Generated by ALICE (Automated Logic Inspection & Code Evaluation)
For questions, contact: {self.admin_email}
"""

        return self._send_email(to_email, subject, body, html_report)

    def send_management_assessment(
        self,
        developer_name: str,
        developer_email: str,
        project_name: str,
        grade: str,
        quality_score: int,
        role_level: str,
        metrics: dict,
        strengths: List[str],
        weaknesses: List[str]
    ) -> bool:
        """
        Send confidential assessment to management

        Args:
            developer_name: Developer name
            developer_email: Developer email
            project_name: Project name
            grade: Letter grade (A+, A, B, etc.)
            quality_score: Numeric score
            role_level: Senior/Mid/Junior
            metrics: Performance metrics
            strengths: List of strengths
            weaknesses: List of weaknesses

        Returns:
            True if sent successfully
        """
        subject = f"Developer Assessment - {developer_name} - Grade {grade} - {datetime.now().strftime('%Y-%m-%d')}"

        # Determine performance rating
        if quality_score >= 90:
            performance_rating = "EXCELLENT PERFORMANCE"
        elif quality_score >= 75:
            performance_rating = "MEETS EXPECTATIONS"
        elif quality_score >= 60:
            performance_rating = "NEEDS IMPROVEMENT"
        else:
            performance_rating = "IMMEDIATE ACTION REQUIRED"

        body = f"""
Developer Performance Assessment
{'=' * 60}

CONFIDENTIAL - MANAGEMENT ONLY

Project: {project_name}
Developer: {developer_name} ({developer_email})
Date: {datetime.now().strftime('%Y-%m-%d')}
Grade: {grade}
Role Level: {role_level}

Code Quality Metrics
--------------------
Quality Score: {quality_score}%
Files Analyzed: {metrics.get('total_files', 0)}
Critical Issues: {metrics.get('critical_bugs', 0)}
High Issues: {metrics.get('high_bugs', 0)}
Medium Issues: {metrics.get('medium_bugs', 0)}
Test Failure Rate: {metrics.get('test_failure_rate', 0)}%

Strengths
---------
"""
        for strength in strengths:
            body += f"- {strength}\n"

        body += f"""
Areas for Improvement
---------------------
"""
        for weakness in weaknesses:
            body += f"- {weakness}\n"

        body += f"""
Performance Rating
------------------
{performance_rating}

"""

        if performance_rating == "IMMEDIATE ACTION REQUIRED":
            body += """
⚠️  ALERT: This assessment indicates serious quality concerns.
Recommend immediate one-on-one discussion and performance improvement plan.

"""

        body += f"""
---
This is a confidential assessment generated by ALICE.
Distribution restricted to management only.
Contact: {self.admin_email}
"""

        return self._send_email(self.admin_email, subject, body)

    def _send_email(
        self,
        to_email: str,
        subject: str,
        body: str,
        html_attachment: Optional[str] = None
    ) -> bool:
        """
        Internal method to send email

        Args:
            to_email: Recipient email
            subject: Email subject
            body: Email body (plain text)
            html_attachment: Optional HTML content to attach

        Returns:
            True if sent successfully
        """
        try:
            msg = MIMEMultipart()
            msg['From'] = self.username
            msg['To'] = to_email
            msg['Subject'] = subject

            # Add body
            msg.attach(MIMEText(body, 'plain'))

            # Add HTML attachment if provided
            if html_attachment:
                html_part = MIMEApplication(html_attachment.encode(), _subtype='html')
                html_part.add_header('Content-Disposition', 'attachment', filename='detailed_report.html')
                msg.attach(html_part)

            # Send email
            with smtplib.SMTP(self.host, self.port) as server:
                server.starttls()
                server.login(self.username, self.password)
                server.send_message(msg)

            return True

        except Exception as e:
            print(f"Error sending email: {e}")
            return False


def get_email_client() -> EmailClient:
    """Get email client instance"""
    return EmailClient()
